### ISSUE TITLE
Travis CI fix/update (my update)

### ISSUE THREAD

**Issue by Montana** [AstraZeneca-NGS/VarDictJava#331]
This improves the current Travis CI YAML instructions that are in place now. Let's make sure this is what it looks like in your `gradle.properties file.`

```bash
org.gradle.caching=true
org.gradle.parallel=true
```

## AstraZeneca's improved NGS .travis.yml file 

```yaml
language: java
dist: trusty
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - $HOME/.gradle/nodejs/
 - node_modules
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11
  - openjdk12
script:
  - ./gradlew build --scan -s # Added by Montana 
  - ./gradlew test jacocoTestReport
  - ./gradlew installDist
  - ./gradlew javadoc
  jobs:
  include:
    - stage: Montana's AstraZeneca optimization
      script: ./gradlew assemble --scan --no-daemon
    - stage: Run Montana's tests 
      script: ./gradlew tests --scan --no-daemon
      script: ./gradlew integration-tests --scan --no-daemon
  ```
